# ?? ??? ?? ??
server:
  port: 8080
  servlet:
    encoding:
      force-response: true

spring:
  # DB ?? ??
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <host>
    username: root
    password: <host>
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # JPA ??
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  secret: hello.world.key